### ISSUE TITLE
Is it possible to combine multiple queries for this solution?

### ISSUE THREAD

**Issue by sabeehshah** [alexmamo/FirestoreRealtimePagination#1]
I was looking at one of your answers in stackoverflow where you show how to combine two queries (i need this for a NOT EQUALS query) and was wondering if its possible within this architecture that you have showed. Which class should handle that? also i need to be able to update the queries dynamically for features such as filter the list with specific records.

**Comment by AlexMamo** [comment]
I think you are referring to this [answer](https://stackoverflow.com/questions/50118345/firestore-merging-two-queries-locally), right? And you can achieve what you want as long as you are always using `startAfter(lastVisibleProduct)` and get the remaining products. If you have hard time implementing that, add a question on Stackoverflow so we can take a look at it.

**Comment by sabeehshah** [comment]
Yes i was referring to that answer but i was wondering if its possible to do the combined task with the clean firestore paging structure article that you posted.

**Comment by sabeehshah** [comment]
I do like the architecture of this specific code repository however i am struggling to filter my query results before passing it to the array list of the view, i want to remove some documents that are returned by the query based on a condition.

**Comment by AlexMamo** [comment]
In that case, you check another repo that filters data https://github.com/alexmamo/FilterFirestoreResults

**Comment by AlexMamo** [comment]
I just answered your [question](https://stackoverflow.com/questions/60906876/how-to-get-last-visible-documentsnapshot-in-a-combined-task-for-firestore-querie/60916331) on StackOverflow ;)
