### ISSUE TITLE
Code runs Perfectly , but the cost of reads (like add, update..) so high??

### ISSUE THREAD

**Issue by Bhumesh-45678** [alexmamo/FirestoreRealtimePagination#6]
Respected Alex Sir,
                               i am copy this code , it works perfectly. But it automatically added documents that the names say Realtime. Think when it uses for commercial , it goes the firestore bills so high. I am new and learning firestore. i want to add some fuctionality like
1) in this code uses the SwipeRefreshLayout . when the user pulls to down then the realtime code will work.

please help me how to add this functionality in this code. Thanks Alex Sir

**Comment by AlexMamo** [comment]
Yes, if want to read the data and always keep it in sync, you'll be billed with a read operation, each time something is added or it's changed. If you don't need the real-time feature when you should consider using this [repo](https://github.com/alexmamo/FirestorePaginationJetpackCompose) and add a refresh option yourself.
